"use client";

import Link from "next/link";
import { motion, useReducedMotion, useScroll, useTransform } from "framer-motion";
import { useRef } from "react";

import { FlowBackground } from "@/components/layout/flow-background";
import { PipelineLogo } from "@/components/layout/pipeline-logo";
import { useAuthSession } from "@/hooks/use-auth-session";
import { hasActiveSubscription } from "@/lib/auth/subscription";

const valueCards = [
  {
    icon: "gen" as const,
    eyebrow: "features/generation",
    title: "Source-backed generation",
    body: "Generate workflow files from templates mapped to real source files in your repos.",
  },
  {
    icon: "cicd" as const,
    eyebrow: "features/automation",
    title: "Automated CI/CD setup",
    body: "Apply service settings and output production-ready YAML in a single guided flow.",
  },
  {
    icon: "agnt" as const,
    eyebrow: "features/agents",
    title: "Multi-agent workflow system",
    body: "Use guided tabs to move from setup to generated workflows and exported templates.",
  },
];

type YamlLineType = "comment" | "key" | "indent1" | "indent2" | "keyword" | "step";

interface YamlLine {
  id: string;
  type: YamlLineType;
  text: string;
  value: string | null;
  valueType: "string" | "raw" | null;
}

const heroYamlLines: YamlLine[] = [
  { id: "l0",  type: "comment",  text: "# Generated by FlowCI Studio", value: null,                    valueType: null     },
  { id: "l1",  type: "key",      text: "name",                          value: "payments-service-ci",   valueType: "string" },
  { id: "l2",  type: "key",      text: "on",                            value: null,                    valueType: null     },
  { id: "l3",  type: "indent1",  text: "push",                          value: null,                    valueType: null     },
  { id: "l4",  type: "indent2",  text: "branches",                      value: '["main", "develop"]',   valueType: "string" },
  { id: "l5",  type: "key",      text: "jobs",                          value: null,                    valueType: null     },
  { id: "l6",  type: "indent1",  text: "build",                         value: null,                    valueType: null     },
  { id: "l7",  type: "indent2",  text: "runs-on",                       value: "ubuntu-latest",         valueType: "string" },
  { id: "l8",  type: "keyword",  text: "steps",                         value: null,                    valueType: null     },
  { id: "l9",  type: "step",     text: "uses",                          value: "actions/checkout@v4",   valueType: "string" },
  { id: "l10", type: "step",     text: "name",                          value: "Run tests",             valueType: "string" },
];

const YAML_INDENT: Record<YamlLineType, string> = {
  comment: "",
  key:     "",
  keyword: "    ",
  indent1: "  ",
  indent2: "    ",
  step:    "      - ",
};

function YamlLineValue({ value, valueType }: Readonly<{ value: string | null; valueType: "string" | "raw" | null }>) {
  if (value === null) {
    return <>:</>;
  }
  if (valueType === "string") {
    return <>{": "}<span className="mockup-string">{value}</span></>;
  }
  return <>{": "}{value}</>;
}

function YamlLineContent({ line }: Readonly<{ line: YamlLine }>) {
  const indent = YAML_INDENT[line.type];

  if (line.type === "comment") {
    return <span className="mockup-comment">{line.text}</span>;
  }
  if (line.type === "keyword") {
    return <>{indent}<span className="mockup-keyword">{line.text}</span>:</>;
  }
  return (
    <>
      {indent}
      <span className="mockup-key">{line.text}</span>
      <YamlLineValue value={line.value} valueType={line.valueType} />
    </>
  );
}

const heroChip = "Powered by source-backed templates";

function GenIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
      <polyline points="14 2 14 8 20 8"/>
      <line x1="16" y1="13" x2="8" y2="13"/>
      <line x1="16" y1="17" x2="8" y2="17"/>
    </svg>
  );
}

function CicdIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <circle cx="12" cy="12" r="3"/>
      <path d="M19.07 4.93a10 10 0 0 1 0 14.14M16.24 7.76a6 6 0 0 1 0 8.49M4.93 4.93a10 10 0 0 0 0 14.14M7.76 7.76a6 6 0 0 0 0 8.49"/>
    </svg>
  );
}

function AgntIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <circle cx="18" cy="18" r="3"/>
      <circle cx="6" cy="6" r="3"/>
      <path d="M13 6h3a2 2 0 0 1 2 2v7"/>
      <line x1="6" y1="9" x2="6" y2="21"/>
    </svg>
  );
}

function CardIcon({ type }: Readonly<{ type: "gen" | "cicd" | "agnt" }>) {
  if (type === "gen") return <GenIcon />;
  if (type === "cicd") return <CicdIcon />;
  return <AgntIcon />;
}

function CheckIcon() {
  return (
    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <polyline points="20 6 9 17 4 12" />
    </svg>
  );
}

const yamlLineVariants = {
  hidden: { opacity: 0, x: -10 },
  visible: { opacity: 1, x: 0 },
};

const mockupContainerVariants = {
  hidden: {},
  visible: {
    transition: { staggerChildren: 0.06, delayChildren: 0.35 },
  },
};

const featureRows = [
  { name: "Workflow generation",   pro: true, enterprise: true },
  { name: "Template access",       pro: true, enterprise: true },
  { name: "Workflow history",      pro: true, enterprise: true },
  { name: "GitHub integration",    pro: true, enterprise: true },
  { name: "Priority support",      pro: false, enterprise: true },
  { name: "Governance defaults",   pro: false, enterprise: true },
];

function PipelineFlowSVG() {
  return (
    <div style={{ width: "100%" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 0, padding: "0.8rem 1rem", background: "rgba(26,86,219,0.04)", borderRadius: 10, border: "1px solid rgba(26,86,219,0.1)" }}>
        {(["Source", "Build", "Test", "Deploy"] as const).map((label, i, arr) => (
          <div key={label} style={{ display: "flex", alignItems: "center", flex: i < arr.length - 1 ? 1 : "none" }}>
            <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: "0.25rem", flexShrink: 0 }}>
              <div style={{
                width: 32,
                height: 32,
                borderRadius: "50%",
                background: label === "Deploy" ? "#12b76a" : "#1a56db",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                animation: `pipelinePulse ${1.2 + i * 0.3}s ease-in-out infinite`,
                boxShadow: label === "Deploy" ? "0 0 0 3px rgba(18,183,106,0.2)" : "0 0 0 3px rgba(26,86,219,0.15)",
              }}>
                <svg width="10" height="10" viewBox="0 0 10 10" fill="none" aria-hidden="true">
                  <polyline points="1.5,5 4,7.5 8.5,2.5" stroke="white" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </div>
              <span style={{ fontSize: "0.7rem", color: "#9399a6", letterSpacing: "0.08em", textTransform: "uppercase" }}>{label}</span>
            </div>
            {i < arr.length - 1 && (
              <div style={{ flex: 1, height: 2, background: "linear-gradient(90deg, #1a56db, rgba(26,86,219,0.3))", margin: "0 0.25rem", marginBottom: "1rem", borderRadius: 999, animation: "pipelineFlow 2s linear infinite" }} />
            )}
          </div>
        ))}
      </div>
      <div style={{ display: "flex", alignItems: "center", gap: "0.4rem", marginTop: "0.4rem", paddingLeft: "0.2rem" }}>
        <div style={{ width: 6, height: 6, borderRadius: "50%", background: "#12b76a", animation: "pipelinePulse 1.5s ease-in-out infinite" }} />
        <span style={{ fontSize: "0.7rem", color: "#9399a6", fontFamily: "ui-monospace, monospace" }}>All checks passed · 2m 14s</span>
      </div>
    </div>
  );
}

const recentActivity = [
  { repo: "payments-api", action: "Deployed to production",    time: "2m ago",  status: "success" },
  { repo: "auth-service",  action: "Tests passed (142/142)",   time: "8m ago",  status: "success" },
  { repo: "frontend",      action: "Build completed",          time: "15m ago", status: "success" },
  { repo: "worker",        action: "Lint + security check",    time: "23m ago", status: "success" },
];

function ActivityStrip() {
  return (
    <div style={{ padding: "clamp(2rem,4vw,3rem) clamp(2rem,6vw,4rem)", borderBottom: "1px solid rgba(0,0,0,0.06)" }}>
      <div style={{ display: "flex", alignItems: "baseline", gap: "0.6rem", marginBottom: "1rem" }}>
        <p style={{ fontFamily: "ui-monospace, monospace", fontSize: "0.72rem", color: "#9399a6", letterSpacing: "0.06em", margin: 0 }}>
          <span style={{ color: "#1a56db" }}>./</span> activity/recent.log
        </p>
        <div style={{ width: 6, height: 6, borderRadius: "50%", background: "#12b76a", display: "inline-block", animation: "pipelinePulse 1.5s ease-in-out infinite" }} />
        <span style={{ fontSize: "0.7rem", color: "#9399a6", fontFamily: "ui-monospace, monospace" }}>live</span>
      </div>
      <div style={{ display: "grid", gap: "0.4rem" }}>
        {recentActivity.map((item) => (
          <div key={item.repo} style={{ display: "flex", alignItems: "center", gap: "0.8rem", padding: "0.55rem 0.8rem", borderRadius: 8, background: "rgba(0,0,0,0.02)", border: "1px solid rgba(0,0,0,0.05)" }}>
            <div style={{ width: 7, height: 7, borderRadius: "50%", background: "#12b76a", flexShrink: 0 }} />
            <span style={{ fontFamily: "ui-monospace, monospace", fontSize: "0.78rem", color: "#0f0f10", fontWeight: 600, minWidth: 110 }}>{item.repo}</span>
            <span style={{ fontSize: "0.8rem", color: "#4a4f5a", flex: 1 }}>{item.action}</span>
            <span style={{ fontSize: "0.72rem", color: "#9399a6", flexShrink: 0, fontFamily: "ui-monospace, monospace" }}>{item.time}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

interface NavLinks {
  primaryHref: string;
  primaryLabel: string;
  appHref: string;
  appLabel: string;
  navUtilityHref: string;
  navUtilityLabel: string;
}

function resolveNavLinks(status: string, hasSubscription: boolean): NavLinks {
  if (status !== "signed-in") {
    return {
      primaryHref:    "/signup",
      primaryLabel:   "Sign up with Google or GitHub",
      appHref:        "/subscribe",
      appLabel:       "Pricing",
      navUtilityHref: "/login",
      navUtilityLabel: "Login",
    };
  }

  const primaryHref  = hasSubscription ? "/home"      : "/subscribe";
  const primaryLabel = hasSubscription ? "Open your workspace" : "Activate 300 pesos plan";

  return {
    primaryHref,
    primaryLabel,
    appHref:         "/home",
    appLabel:        "Dashboard",
    navUtilityHref:  "/home",
    navUtilityLabel: "Home",
  };
}

export default function LandingPage() {
  const prefersReducedMotion = useReducedMotion();
  const { status, session } = useAuthSession();
  const hasSubscription = hasActiveSubscription(session);

  const heroRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({ target: heroRef, offset: ["start start", "end start"] });
  const heroY = useTransform(scrollYProgress, [0, 1], ["0%", "12%"]);

  const {
    primaryHref,
    primaryLabel,
    appHref,
    appLabel,
    navUtilityHref,
    navUtilityLabel,
  } = resolveNavLinks(status, hasSubscription);

  return (
    <main className="landing-page-shell">
      <a href="#main-content" className="skip-link">Skip to main content</a>
      <FlowBackground />

      {/* Full-width sticky nav bar */}
      <header className="marketing-nav">
        <div className="brand-mark">
          <PipelineLogo size={26} />
          <span>FlowCI Studio</span>
        </div>
        <nav aria-label="Primary" className="nav-links">
          <Link href="/workflows">Workflows</Link>
        </nav>
        <div className="landing-nav-actions">
          <Link className="ghost-button" href={navUtilityHref}>
            {navUtilityLabel}
          </Link>
          <Link className="primary-button" href={appHref}>
            {appLabel}
          </Link>
        </div>
      </header>

      <div id="main-content">
        {/* ── Split hero ─────────────────────────────────────────────── */}
        <section
          className="landing-split"
          ref={heroRef}
          aria-label="Main message"
        >
          {/* Left panel */}
          <motion.div
            className="landing-split-left"
            style={prefersReducedMotion ? undefined : { y: heroY }}
          >
            <p className="file-path-label">workflows/generate.yml</p>

            <motion.p
              className="hero-chip edge-accent"
              initial={prefersReducedMotion ? undefined : { opacity: 0, y: 10 }}
              animate={prefersReducedMotion ? undefined : { opacity: 1, y: 0 }}
            >
              {heroChip}
            </motion.p>

            <motion.h1
              initial={prefersReducedMotion ? undefined : { opacity: 0, y: 20 }}
              animate={prefersReducedMotion ? undefined : { opacity: 1, y: 0 }}
              transition={{ duration: 0.42 }}
              style={{ fontSize: "clamp(2.8rem,5.5vw,4.8rem)", fontWeight: 800, letterSpacing: "-0.035em", lineHeight: 1.05, margin: 0 }}
            >
              Build production-ready workflows{" "}
              <span className="hero-highlight">instantly</span>
            </motion.h1>

            <motion.p
              className="hero-description"
              initial={prefersReducedMotion ? undefined : { opacity: 0, y: 18 }}
              animate={prefersReducedMotion ? undefined : { opacity: 1, y: 0 }}
              transition={{ duration: 0.48, delay: 0.08 }}
            >
              Transform service requirements into complete CI/CD pipelines with agent-guided setup,
              generation, and export in one place.
            </motion.p>

            {/* Inline stats */}
            <motion.div
              className="stats-row"
              initial={prefersReducedMotion ? undefined : { opacity: 0, y: 14 }}
              animate={prefersReducedMotion ? undefined : { opacity: 1, y: 0 }}
              transition={{ duration: 0.42, delay: 0.12 }}
            >
              <div className="stat-block">
                <span className="stat-number">40+</span>
                <span className="stat-label">Templates</span>
              </div>
              <div className="stat-block">
                <span className="stat-number" style={{ fontSize: "1.3rem" }}>&lt;&nbsp;2 min</span>
                <span className="stat-label">Setup time</span>
              </div>
              <div className="stat-block">
                <span className="stat-number">100%</span>
                <span className="stat-label">GitHub native</span>
              </div>
            </motion.div>

            <motion.div
              className="hero-actions"
              initial={prefersReducedMotion ? undefined : { opacity: 0, y: 20 }}
              animate={prefersReducedMotion ? undefined : { opacity: 1, y: 0 }}
              transition={{ duration: 0.45, delay: 0.15 }}
            >
              <Link className="primary-button" href={primaryHref}>
                {primaryLabel}
              </Link>
              <Link className="ghost-button" href="/subscribe">
                View pricing
              </Link>
            </motion.div>
          </motion.div>

          {/* Right panel — pipeline strip + YAML terminal stacked and aligned */}
          <div className="landing-split-right">
            {/* Pipeline strip — full width of content area */}
            <div style={{ width: "100%", maxWidth: 520 }}>
              <PipelineFlowSVG />
            </div>

            {/* YAML terminal — same width, directly below pipeline strip */}
            <motion.div
              className="hero-mockup"
              style={{ width: "100%", maxWidth: 520 }}
              initial={prefersReducedMotion ? undefined : { opacity: 0, y: 24, scale: 0.97 }}
              animate={prefersReducedMotion ? undefined : { opacity: 1, y: 0, scale: 1 }}
              transition={{ duration: 0.55, delay: 0.25, ease: [0.22, 1, 0.36, 1] }}
            >
              {/* macOS title bar */}
              <div className="hero-mockup-bar">
                <span className="mockup-dot mockup-dot-red" aria-hidden="true" />
                <span className="mockup-dot mockup-dot-yellow" aria-hidden="true" />
                <span className="mockup-dot mockup-dot-green" aria-hidden="true" />
                <span style={{ fontFamily: "ui-monospace, monospace", fontSize: "0.7rem", color: "rgba(255,255,255,0.35)", marginLeft: "0.5rem" }}>payments-service.yml</span>
              </div>
              <motion.pre
                aria-label="Example generated YAML workflow"
                variants={prefersReducedMotion ? undefined : mockupContainerVariants}
                initial={prefersReducedMotion ? undefined : "hidden"}
                animate={prefersReducedMotion ? undefined : "visible"}
              >
                {heroYamlLines.map((line) => (
                  <motion.span
                    key={line.id}
                    variants={prefersReducedMotion ? undefined : yamlLineVariants}
                    transition={{ duration: 0.28, ease: "easeOut" }}
                    style={{ display: "block" }}
                  >
                    <YamlLineContent line={line} />
                  </motion.span>
                ))}
              </motion.pre>
            </motion.div>
          </div>
        </section>

        {/* ── Features strip ─────────────────────────────────────────── */}
        <section className="features-strip" aria-label="Key features">
          {valueCards.map((card, index) => (
            <motion.div
              key={card.title}
              className="feature-strip-item"
              initial={prefersReducedMotion ? undefined : { opacity: 0, y: 16 }}
              animate={prefersReducedMotion ? undefined : { opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1, duration: 0.38 }}
            >
              <p className="file-path-label">{card.eyebrow}</p>
              <span style={{
                display: "inline-flex",
                alignItems: "center",
                justifyContent: "center",
                width: "2rem",
                height: "2rem",
                borderRadius: "0.5rem",
                border: "1px solid rgba(26,86,219,0.2)",
                background: "var(--brand-light)",
                color: "var(--brand)",
                marginBottom: "0.1rem",
              }} aria-hidden="true">
                <CardIcon type={card.icon} />
              </span>
              <h3>{card.title}</h3>
              <p>{card.body}</p>
            </motion.div>
          ))}
        </section>

        {/* ── Activity strip ─────────────────────────────────────────── */}
        <ActivityStrip />

        {/* ── Pricing ────────────────────────────────────────────────── */}
        <section
          id="pricing"
          style={{ padding: "clamp(2rem, 5vw, 4rem) clamp(1rem, 4vw, 3rem)" }}
          aria-label="Pricing plans"
        >
          <p className="section-divider">pricing</p>
          <p className="file-path-label" style={{ marginBottom: "0.75rem" }}>billing/plans.yml</p>
          <h2 style={{ fontSize: "clamp(1.5rem, 3vw, 2.4rem)", marginBottom: "1.5rem" }}>Simple monthly plans</h2>

          {/* Comparison table */}
          <div className="pricing-table">
            {/* Header row */}
            <div className="pricing-table-header pricing-table-empty" />
            <div className="pricing-table-header">
              <p className="pricing-table-plan-label">Pro Monthly</p>
              <p className="pricing-table-price">₱300</p>
              <p style={{ fontSize: "0.78rem", color: "var(--text-muted)", margin: "0.3rem 0 0.75rem" }}>per month</p>
              <Link className="primary-button" href="/signup" style={{ fontSize: "0.82rem", padding: "0.45rem 0.9rem", minHeight: "2.4rem" }}>
                Start for ₱300/mo
              </Link>
            </div>
            <div className="pricing-table-header" style={{ borderLeft: "none" }}>
              <p className="pricing-table-plan-label">Enterprise Monthly</p>
              <p className="pricing-table-price enterprise">₱1,200</p>
              <p style={{ fontSize: "0.78rem", color: "var(--text-muted)", margin: "0.3rem 0 0.75rem" }}>per month</p>
              <Link className="ghost-button" href="/login" style={{ fontSize: "0.82rem", padding: "0.45rem 0.9rem", minHeight: "2.4rem" }}>
                Already a member
              </Link>
            </div>

            {/* Feature rows */}
            {featureRows.map((row) => (
              <div key={row.name} style={{ display: "contents" }}>
                <div className="pricing-table-cell feature-name">{row.name}</div>
                <div className={`pricing-table-cell${row.pro ? " check" : ""}`}>
                  {row.pro ? <CheckIcon /> : <span style={{ color: "var(--text-muted)" }}>—</span>}
                </div>
                <div className={`pricing-table-cell${row.enterprise ? " check" : ""}`}>
                  {row.enterprise ? <CheckIcon /> : <span style={{ color: "var(--text-muted)" }}>—</span>}
                </div>
              </div>
            ))}
          </div>
        </section>
      </div>
    </main>
  );
}
